[project]
name = "home-bin"
version = "0.1.0"
requires-python = ">=3.11"

[project.scripts]
home = "home_cli:main"
list-applications = "list_applications:main"
list-repositories = "list_repositories:main"
list-safari-bookmarks = "list_safari_bookmarks:main"
quick-access-bookmarks = "quick_access_bookmarks:main"
quick-access-clipboard = "quick_access_clipboard:main"
quick-access-emojis = "quick_access_emojis:main"
quick-access-home = "quick_access_home:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
include = [
  "*.py",
  "lib/home/**",
  "lib/safari_bookmarks/**",
]

[tool.hatch.build.targets.wheel.sources]
"lib" = ""
