[hammerspoon]
target = "~/.hammerspoon"
labels = ["macos"]

[fish]
target = "~/.config/fish"
labels = [["macos", "linux"], "cli"]

[fresh]
target = "~/.config/fresh"
labels = [["macos", "linux"], "cli"]

[[ghostty]]
source = "config/ghostty/shared"
target = "~/Library/Application Support/com.mitchellh.ghostty"
labels = ["macos", "cli"]

[[ghostty]]
source = "config/ghostty/macos"
target = "~/.config/ghostty-macos"
labels = ["macos", "cli"]

[[ghostty]]
source = "config/ghostty/linux"
target = "~/.config/ghostty-linux"
labels = ["linux", "cli"]

[[ghostty]]
source = "config/ghostty/shared"
target = "~/.config/ghostty"
labels = ["linux", "cli"]

[[mise]]
source = "config/mise/config.toml"
target = "~/.config/mise.toml"
labels = ["cli"]

[[mise]]
source = "config/mise/config-macos.toml"
target = "~/.config/mise/conf.d/config-macos.toml"
labels = ["macos", "cli"]

[[mise]]
source = "config/mise/ai.toml"
target = "~/.config/mise/conf.d/ai.toml"
labels = ["ai"]

[[mise]]
source = "config/mise/dev.toml"
target = "~/.config/mise/conf.d/dev.toml"
labels = ["dev"]

[[mise]]
source = "config/mise/media.toml"
target = "~/.config/mise/conf.d/media.toml"
labels = ["media"]

[[mise]]
source = "config/mise/work.toml"
target = "~/.config/mise/conf.d/work.toml"
labels = ["work"]

[[mise]]
source = "config/mise/dev-apple.toml"
target = "~/.config/mise/conf.d/dev-apple.toml"
labels = ["dev-apple"]

[[claude]]
source = "config/claude/commands"
target = "~/.claude/commands"
labels = ["ai"]

[[claude]]
source = "config/claude/rules"
target = "~/.claude/rules"
labels = ["ai"]

[[claude]]
source = "config/claude/skills"
target = "~/.claude/skills"
labels = ["ai"]

[kitty]
target = "~/.config/kitty"
labels = ["macos", "cli"]

[[starship]]
source = "config/starship/starship.toml"
target = "~/.config/starship.toml"
labels = ["cli"]

[[xccolortheme]]
source = "externals/daltonmenezes/aura-theme/packages/xcode/Aura Soft Dark.xccolortheme"
target = "~/Library/Developer/Xcode/UserData/FontAndColorThemes/Favorite.xccolortheme"
labels = ["macos", "dev-apple"]

[test]
target = "~/.test"
labels = ["test"]
