[tools]
bat = "latest"
fastfetch = "latest"
fzf = "latest"
go = "latest"
jq = "latest"
tmux = "3.6a"
node = "lts"
yazi = "latest"
yq = "latest"
"github:da-luce/astroterm" = "latest"
"go:github.com/savedra1/clipse" = "latest"
"npm:figlet" = "latest"

[env]
GOPATH = "{{env.HOME}}/.home/cache/go"
GOMODCACHE = "{{env.HOME}}/.home/cache/go-mod-cache"
NPM_CONFIG_CACHE = "{{env.HOME}}/.home/cache/npm-cache"
NPM_CONFIG_PREFIX = "{{env.HOME}}/.home/cache/npm-global"
npm_config_devdir = "{{env.HOME}}/.home/cache/npm-gyp"
