[tools]
bat = "latest"
fastfetch = "latest"
fzf = "latest"
go = "latest"
jq = "latest"
node = "lts"
python = "latest"
tmux = "3.6a"
uv = "latest"
yazi = "latest"
yq = "latest"
"github:da-luce/astroterm" = "latest"
# "go:github.com/savedra1/clipse" = "latest"
"npm:@fresh-editor/fresh-editor" = "latest"
"npm:figlet" = "latest"

[env]
GOPATH = "{{env.HOME}}/.home/cache/go"
GOMODCACHE = "{{env.HOME}}/.home/cache/go-mod-cache"
NODE_GYP_FORCE_PYTHON = "{{env.HOME}}/.home/cache/node-gyp"
NPM_CONFIG_CACHE = "{{env.HOME}}/.home/cache/npm-cache"
NPM_CONFIG_PREFIX = "{{env.HOME}}/.home/cache/npm-global"
UV_CACHE_DIR = "{{env.HOME}}/.home/cache/uv-cache"
UV_TOOL_BIN_DIR = "{{env.HOME}}/.home/cache/uv-bin"
UV_TOOL_DIR = "{{env.HOME}}/.home/cache/uv-tools"
