[tools]
bat = "latest"
fzf = "latest"
go = "latest"
node = "lts"
jq = "latest"
"npm:figlet" = "latest"
yazi = "latest"
"go:github.com/savedra1/clipse" = "latest"

[env]
GOPATH = "{{env.HOME}}/.home/cache/go"
GOMODCACHE = "{{env.HOME}}/.home/cache/go-mod-cache"
NPM_CONFIG_CACHE = "{{env.HOME}}/.home/cache/npm-cache"
NPM_CONFIG_PREFIX = "{{env.HOME}}/.home/cache/npm-global"
npm_config_devdir = "{{env.HOME}}/.home/cache/npm-gyp"
